export const CREATE = "Create";
export const UPDATE = "Update";
export const EDIT = "Edit";
export const CREATEAGENT = "Create Agent";
export const EDITAGENT = "Edit Agent";
export const SIGNIN = "Sign In";
export const ONLINE = "Online";
export const OFFLINE = "Offline";
export const DEFAULTAVATAR = "https://github.com/shadcn.png";
